/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 31-May-2021 21:08:07 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Venta" CASCADE
;

DROP TABLE IF EXISTS "Telefono" CASCADE
;

DROP TABLE IF EXISTS "Producto" CASCADE
;

DROP TABLE IF EXISTS "PersonaTelefono" CASCADE
;

DROP TABLE IF EXISTS "Persona" CASCADE
;

DROP TABLE IF EXISTS "Pago" CASCADE
;

DROP TABLE IF EXISTS "Item" CASCADE
;

DROP TABLE IF EXISTS "Empleado" CASCADE
;

DROP TABLE IF EXISTS "Email" CASCADE
;

DROP TABLE IF EXISTS "Cliente" CASCADE
;

/* Create Tables */

CREATE TABLE "Venta"
(
	"numero" bigint NOT NULL,
	"fecha" date NULL,
	"legajo" bigint NULL,
	"dni_empleado" bigint NULL,
	"codigo" bigint NULL,
	"dni_cliente" bigint NULL
)
;

CREATE TABLE "Telefono"
(
	"id_telefono" bigint NOT NULL,
	"numero" varchar(50)	 NULL
)
;

CREATE TABLE "Producto"
(
	"id_producto" bigint NOT NULL,
	"descripcion" varchar(50)	 NULL,
	"precio" decimal NULL
)
;

CREATE TABLE "PersonaTelefono"
(
	"dni" bigint NOT NULL,
	"id_telefono" bigint NOT NULL
)
;

CREATE TABLE "Persona"
(
	"dni" bigint NOT NULL,
	"apellido" varchar(50)	 NULL,
	"nombre" varchar(50)	 NULL
)
;

CREATE TABLE "Pago"
(
	"codigo_pago" bigint NOT NULL,
	"monto" decimal NULL,
	"numero" bigint NOT NULL
)
;

CREATE TABLE "Item"
(
	"numero" bigint NOT NULL,
	"id_producto" bigint NOT NULL
)
;

CREATE TABLE "Empleado"
(
	"legajo" bigint NOT NULL,
	"dni" bigint NOT NULL
)
;

CREATE TABLE "Email"
(
	"id_email" bigint NOT NULL,
	"direccion" varchar(50)	 NULL,
	"dni" bigint NULL
)
;

CREATE TABLE "Cliente"
(
	"codigo" bigint NOT NULL,
	"dni" bigint NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Venta" ADD CONSTRAINT "PK_Venta"
	PRIMARY KEY ("numero")
;

CREATE INDEX "IXFK_Venta_Cliente" ON "Venta" ("codigo" ASC,"dni_cliente" ASC)
;

CREATE INDEX "IXFK_Venta_Empleado" ON "Venta" ("legajo" ASC,"dni_empleado" ASC)
;

ALTER TABLE "Telefono" ADD CONSTRAINT "PK_Telefono"
	PRIMARY KEY ("id_telefono")
;

ALTER TABLE "Producto" ADD CONSTRAINT "PK_Producto"
	PRIMARY KEY ("id_producto")
;

ALTER TABLE "PersonaTelefono" ADD CONSTRAINT "PK_PersonaTelefono"
	PRIMARY KEY ("dni","id_telefono")
;

CREATE INDEX "IXFK_PersonaTelefono_Persona" ON "PersonaTelefono" ("dni" ASC)
;

CREATE INDEX "IXFK_PersonaTelefono_Telefono" ON "PersonaTelefono" ("id_telefono" ASC)
;

ALTER TABLE "Persona" ADD CONSTRAINT "PK_Persona"
	PRIMARY KEY ("dni")
;

ALTER TABLE "Pago" ADD CONSTRAINT "PK_Pago"
	PRIMARY KEY ("codigo_pago","numero")
;

CREATE INDEX "IXFK_Pago_Venta" ON "Pago" ("numero" ASC)
;

ALTER TABLE "Item" ADD CONSTRAINT "PK_Item"
	PRIMARY KEY ("numero","id_producto")
;

CREATE INDEX "IXFK_Item_Producto" ON "Item" ("id_producto" ASC)
;

CREATE INDEX "IXFK_Item_Venta" ON "Item" ("numero" ASC)
;

ALTER TABLE "Empleado" ADD CONSTRAINT "PK_Empleado"
	PRIMARY KEY ("legajo","dni")
;

CREATE INDEX "IXFK_Empleado_Persona" ON "Empleado" ("dni" ASC)
;

ALTER TABLE "Email" ADD CONSTRAINT "PK_Email"
	PRIMARY KEY ("id_email")
;

CREATE INDEX "IXFK_Email_Persona" ON "Email" ("dni" ASC)
;

ALTER TABLE "Cliente" ADD CONSTRAINT "PK_Cliente"
	PRIMARY KEY ("codigo","dni")
;

CREATE INDEX "IXFK_Cliente_Persona" ON "Cliente" ("dni" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Venta" ADD CONSTRAINT "FK_Venta_Cliente"
	FOREIGN KEY ("codigo","dni_cliente") REFERENCES "Cliente" ("codigo","dni") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Venta" ADD CONSTRAINT "FK_Venta_Empleado"
	FOREIGN KEY ("legajo","dni_empleado") REFERENCES "Empleado" ("legajo","dni") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "PersonaTelefono" ADD CONSTRAINT "FK_PersonaTelefono_Persona"
	FOREIGN KEY ("dni") REFERENCES "Persona" ("dni") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "PersonaTelefono" ADD CONSTRAINT "FK_PersonaTelefono_Telefono"
	FOREIGN KEY ("id_telefono") REFERENCES "Telefono" ("id_telefono") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Pago" ADD CONSTRAINT "FK_Pago_Venta"
	FOREIGN KEY ("numero") REFERENCES "Venta" ("numero") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Item" ADD CONSTRAINT "FK_Item_Producto"
	FOREIGN KEY ("id_producto") REFERENCES "Producto" ("id_producto") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Item" ADD CONSTRAINT "FK_Item_Venta"
	FOREIGN KEY ("numero") REFERENCES "Venta" ("numero") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Empleado" ADD CONSTRAINT "FK_Empleado_Persona"
	FOREIGN KEY ("dni") REFERENCES "Persona" ("dni") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Email" ADD CONSTRAINT "FK_Email_Persona"
	FOREIGN KEY ("dni") REFERENCES "Persona" ("dni") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Cliente" ADD CONSTRAINT "FK_Cliente_Persona"
	FOREIGN KEY ("dni") REFERENCES "Persona" ("dni") ON DELETE No Action ON UPDATE No Action
;
